
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_education_platform?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: yangpengfei321
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /**
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.felix.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
