
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_education_platform?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: yangpengfei321
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /**
